import Head from 'next/head'
import Header from '../components/Header'
import { useSession } from "next-auth/react"
import Login from '../components/Login';
import Sidebar from '../components/Sidebar';
import Feed from '../components/Feed';
import Widgets from '../components/Widgets';

export default function Home() {
  const { data: session } = useSession();

  if(!session){
    return <Login />;
  }
  return (
    <div className='h-screen overflow-hidden bg-gray-100'>
      <Head>
        <title>Facebook Clone Daniel</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* header */}
      <Header />

      <main className='flex'>
        {/* sidebar */}
        <Sidebar />
        {/* feed */}
        <Feed />
        {/* widgets */}
        <Widgets />
      </main>
    </div>
  )
}


// export async function getServerSideProps(context) {
//   // get the user
//   const session = getSession(context);

//   return{
//     props:{
//       session
//     }
//   }
// }